services:
  - type: web
    name: nexusreserve-api
    runtime: docker
    plan: free
    dockerfilePath: ./docker/render/backend.Dockerfile
    dockerContext: .
    healthCheckPath: /up
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: NexusReserve
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        sync: false
      - key: APP_URL
        sync: false
      - key: FRONTEND_URL
        value: https://nexus-reserve.netlify.app
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: AIVEN_CA_PEM
        sync: false
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_STORE
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: BROADCAST_CONNECTION
        value: log
      - key: SANCTUM_STATEFUL_DOMAINS
        value: nexus-reserve.netlify.app
      - key: RUN_MIGRATIONS
        value: "true"
      - key: RUN_SEEDERS
        value: "false"
